version: 2

sources:
  - name: looker_demo
    loader: looker_extractor
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: created_at
    tables:
      - name: distribution_centers
        freshness: null
      - name: inventory_items
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
      - name: products
        freshness: null

  - name: analytics_raw
    schema: raw
    loader: internal
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: loaded_at
    tables:
      - name: ad_spend_raw
      - name: customer_conversions_raw
      - name: sessions_raw
